services:
    # Agents
    XApi\LrsBundle\Controller\AgentGetController:
        arguments:
            - '@XApi\LrsBundle\Service\ProfileRequestParser'
        tags:
            - { name: 'controller.service_arguments' }

    # Profiles
    XApi\LrsBundle\Service\ProfileService:
        arguments:
            - '@XApi\Repository\Api\ProfileRepositoryInterface'
            - '@XApi\LrsBundle\Service\ProfileRequestParser'

    XApi\LrsBundle\Controller\ProfileGetController:
        arguments:
            - '@XApi\LrsBundle\Service\ProfileService'
        tags:
            - { name: 'controller.service_arguments' }

    XApi\LrsBundle\Controller\ProfilePostController:
        arguments:
            - '@XApi\LrsBundle\Service\ProfileService'
        tags:
            - { name: 'controller.service_arguments' }

    XApi\LrsBundle\Controller\ProfilePutController:
        arguments:
            - '@XApi\LrsBundle\Service\ProfileService'
        tags:
            - { name: 'controller.service_arguments' }

    XApi\LrsBundle\Controller\ProfileDeleteController:
        arguments:
            - '@XApi\LrsBundle\Service\ProfileService'
        tags:
            - { name: 'controller.service_arguments' }

    XApi\LrsBundle\Controller\ProfileOptionsController:
        tags:
            - { name: 'controller.service_arguments' }

    # About
    XApi\LrsBundle\Controller\AboutGetController:
        tags:
            - { name: 'controller.service_arguments' }

    XApi\LrsBundle\Controller\AboutOptionsController:
        tags:
            - { name: 'controller.service_arguments' }

    # Activity
    XApi\LrsBundle\Controller\ActivityGetController:
        arguments:
            - '@XApi\Repository\Api\ActivityRepositoryInterface'
            - '@Xabbuh\XApi\Serializer\ActivitySerializerInterface'
        tags:
            - { name: 'controller.service_arguments' }

    XApi\LrsBundle\Controller\ActivityOptionsController:
        tags:
            - { name: 'controller.service_arguments' }

    # State
    XApi\LrsBundle\Controller\StateGetController:
        arguments:
            - '@XApi\Repository\Api\StateRepositoryInterface'
        tags:
            - { name: 'controller.service_arguments' }

    XApi\LrsBundle\Controller\StateOptionsController:
        tags:
            - { name: 'controller.service_arguments' }

    XApi\LrsBundle\Controller\StatePostController:
        arguments:
            - '@XApi\Repository\Api\StateRepositoryInterface'
        tags:
            - { name: 'controller.service_arguments' }

    XApi\LrsBundle\Controller\StatePutController:
        arguments:
            - '@XApi\Repository\Api\StateRepositoryInterface'
        tags:
            - { name: 'controller.service_arguments' }

    XApi\LrsBundle\Controller\StateDeleteController:
        arguments:
            - '@XApi\Repository\Api\StateRepositoryInterface'
        tags:
            - { name: 'controller.service_arguments' }

    # Statement
    XApi\LrsBundle\Service\StatementFormatNormalizer:
        arguments:
            - '@XApi\Repository\Api\ActivityRepositoryInterface'
            - '@XApi\Repository\Api\VerbRepositoryInterface'
            - '@Xabbuh\XApi\Serializer\ActivitySerializerInterface'

    XApi\LrsBundle\Service\StatementGetQueryValidator:
        arguments:
            - '@XApi\LrsBundle\Model\StatementsFilterFactory'

    XApi\LrsBundle\Service\StatementContinuationManager:
        arguments:
            - '@cache.app'
            - '@router'

    XApi\LrsBundle\Controller\StatementGetController:
        arguments:
            - '@XApi\Repository\Api\StatementRepositoryInterface'
            - '@Xabbuh\XApi\Serializer\StatementResultSerializerInterface'
            - '@Xabbuh\XApi\Serializer\StatementSerializerInterface'
            - '@XApi\LrsBundle\Service\StatementFormatNormalizer'
            - '@XApi\LrsBundle\Service\StatementGetQueryValidator'
            - '@XApi\LrsBundle\Service\StatementContinuationManager'
        tags:
            - { name: 'controller.service_arguments' }

    XApi\LrsBundle\Controller\StatementOptionsController:
        tags:
            - { name: 'controller.service_arguments' }

    XApi\LrsBundle\Controller\StatementPostController:
        arguments:
            - '@XApi\Repository\Api\StatementRepositoryInterface'
        tags:
            - { name: 'controller.service_arguments' }

    XApi\LrsBundle\Controller\StatementPutController:
        arguments:
            - '@XApi\Repository\Api\StatementRepositoryInterface'
        tags:
            - { name: 'controller.service_arguments' }
