services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    XApi\Repository\Doctrine\Repository\ActivityRepository:
        arguments:
            - '@XApi\Repository\ORM\StatementObjectRepository'

    XApi\Repository\Doctrine\Repository\ProfileRepository:
        arguments:
            - '@XApi\Repository\ORM\ProfileRepository'

    XApi\Repository\Doctrine\Repository\StateRepository:
        arguments:
            - '@XApi\Repository\ORM\StateRepository'

    XApi\Repository\Doctrine\Repository\StatementRepository:
        arguments:
            - '@XApi\Repository\ORM\StatementRepository'

    XApi\Repository\Doctrine\Repository\VerbRepository:
        arguments:
            - '@XApi\Repository\ORM\VerbRepository'
