services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    XApi\LrsBundle\EventListener\AlternateRequestSyntaxListener: ~

    XApi\LrsBundle\EventListener\ExceptionListener: ~

    XApi\LrsBundle\EventListener\HeadersListener:
        arguments:
            - '@XApi\LrsBundle\Service\RequestMatcher'
            - '%xapi_lrs_allowed_origins%'

    XApi\LrsBundle\EventListener\SerializerListener: ~

    XApi\LrsBundle\EventListener\VersionListener: ~
