services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Profile Repository
    XApi\Repository\Doctrine\Mapping\Profile:
        class: Doctrine\ORM\Mapping\ClassMetadata
        factory: [ '@Doctrine\Persistence\ObjectManager', 'getClassMetadata' ]
        arguments:
            - 'XApi\Repository\Doctrine\Mapping\Profile'

    XApi\Repository\ORM\ProfileRepository:
        arguments:
            - '@Doctrine\Persistence\ObjectManager'
            - '@XApi\Repository\Doctrine\Mapping\Profile'

    # State Repository
    XApi\Repository\Doctrine\Mapping\State:
        class: Doctrine\ORM\Mapping\ClassMetadata
        factory: [ '@Doctrine\Persistence\ObjectManager', 'getClassMetadata' ]
        arguments:
            - 'XApi\Repository\Doctrine\Mapping\State'

    XApi\Repository\ORM\StateRepository:
        arguments:
            - '@Doctrine\Persistence\ObjectManager'
            - '@XApi\Repository\Doctrine\Mapping\State'

    # Statement Repository
    XApi\Repository\Doctrine\Mapping\Statement:
        class: Doctrine\ORM\Mapping\ClassMetadata
        factory: [ '@Doctrine\Persistence\ObjectManager', 'getClassMetadata' ]
        arguments:
            - 'XApi\Repository\Doctrine\Mapping\Statement'

    XApi\Repository\ORM\StatementRepository:
        arguments:
            - '@Doctrine\Persistence\ObjectManager'
            - '@XApi\Repository\Doctrine\Mapping\Statement'

    # StatementObject Repository
    XApi\Repository\Doctrine\Mapping\StatementObject:
        class: Doctrine\ORM\Mapping\ClassMetadata
        factory: [ '@Doctrine\Persistence\ObjectManager', 'getClassMetadata' ]
        arguments:
            - 'XApi\Repository\Doctrine\Mapping\StatementObject'

    XApi\Repository\ORM\StatementObjectRepository:
        arguments:
            - '@Doctrine\Persistence\ObjectManager'
            - '@XApi\Repository\Doctrine\Mapping\StatementObject'

    # Verb Repository
    XApi\Repository\Doctrine\Mapping\Verb:
        class: Doctrine\ORM\Mapping\ClassMetadata
        factory: [ '@Doctrine\Persistence\ObjectManager', 'getClassMetadata' ]
        arguments:
            - 'XApi\Repository\Doctrine\Mapping\Verb'

    XApi\Repository\ORM\VerbRepository:
        arguments:
            - '@Doctrine\Persistence\ObjectManager'
            - '@XApi\Repository\Doctrine\Mapping\Verb'
