services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Symfony\Component\Serializer\SerializerInterface:
        factory: [ 'Xabbuh\XApi\Serializer\Symfony\Serializer', 'createSerializer' ]

    Xabbuh\XApi\Serializer\Symfony\SerializerFactory:
        arguments:
            - '@Symfony\Component\Serializer\SerializerInterface'

    Xabbuh\XApi\Serializer\ActivitySerializerInterface:
        factory: [ '@Xabbuh\XApi\Serializer\Symfony\SerializerFactory', 'createActivitySerializer' ]

    Xabbuh\XApi\Serializer\ActorSerializerInterface:
        factory: [ '@Xabbuh\XApi\Serializer\Symfony\SerializerFactory', 'createActorSerializer' ]

    Xabbuh\XApi\Serializer\DocumentDataSerializerInterface:
        factory: [ '@Xabbuh\XApi\Serializer\Symfony\SerializerFactory', 'createDocumentDataSerializer' ]

    Xabbuh\XApi\Serializer\StateSerializerInterface:
        factory: [ '@Xabbuh\XApi\Serializer\Symfony\SerializerFactory', 'createStateSerializer' ]

    Xabbuh\XApi\Serializer\StateDocumentSerializerInterface:
        factory: [ '@Xabbuh\XApi\Serializer\Symfony\SerializerFactory', 'createStateDocumentSerializer' ]

    Xabbuh\XApi\Serializer\PersonSerializerInterface:
        factory: [ '@Xabbuh\XApi\Serializer\Symfony\SerializerFactory', 'createPersonSerializer' ]

    Xabbuh\XApi\Serializer\StatementSerializerInterface:
        factory: [ '@Xabbuh\XApi\Serializer\Symfony\SerializerFactory', 'createStatementSerializer' ]

    Xabbuh\XApi\Serializer\StatementResultSerializerInterface:
        factory: [ '@Xabbuh\XApi\Serializer\Symfony\SerializerFactory', 'createStatementResultSerializer' ]
